version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ulusan
      POSTGRES_PASSWORD: ulusan
      POSTGRES_DB: uav_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: baykar@baykar.com
      PGADMIN_DEFAULT_PASSWORD: baykar
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
